### ISSUE TITLE
No response to SSDP search/discover packets on IPv6

### ISSUE THREAD

**Issue by chrsmrtnx** [pupnp/pupnp#113]
(This is a follow-up to [this gerbera bug report](https://github.com/gerbera/gerbera/issues/442) where it was suggested that the gerbera issue I'm having may be rooted in pupnp.)

Using gerbera, built with pupnp 1.8.4 on Debian buster, the gerbera daemon binds to my LAN-facing interface as configured. For IPv6, it binds to the applicable link-local address.

VLC, on a different client machine, when searching for DLNA services on the LAN, sends out SSDP queries using both IPv4 and IPv6 (ff02::c and ff05::c). Oddly, gerbera only responds on IPv4. It receives the IPv6 packets sent to ff02::c (according to debug output), and the daemon's HTTP interface is up and reachable on IPv6, but the daemon doesn't respond to VLC (except on IPv4). Thus if IPv4 is firewalled-off, VLC can't find gerbera on the LAN.

Is this intentional, a bug, or does gerbera simply not fully support the IPv6 capabilities available in pupnp? To quote the gerbera bug report linked to above: "I cant see anywhere we do anything odd, in the case you pass an interface name we pass that straight into libupnp's UpnpInit2 function."

Grateful for any assistance.

**Comment by BraneDev** [comment]
I found this same issue.  I replaced all instances of INET_IPV6 with UPNP_ENABLE_IPV6 in the code and rebuilt the library.  Now I have SSDP over IPv6.

**Comment by mrjimenez** [comment]
Hi BraneDev,

It seems like we have a problem indeed. INET_IPV6 is used in two source files:
upnp/src/ssdp/ssdp_device.c
upnp/src/inet_pton.c

The last one is windows only, and INET_IPV6 is defined in upnp/src/inc/inet_pton.h, so it seems ok here. But upnp/src/ssdp/ssdp_device.c seems wrong to me. If no one opposes, I will patch it.

Regards,
Marcelo.

**Comment by Vollstrecker** [comment]
Is this still an issue?

**Comment by mrjimenez** [comment]
Fixed in b096700dcd1e69817e6e1cc39483f72e4599b9d1
