### ISSUE TITLE
1.8.6 Tarball issues with automake 1.16

### ISSUE THREAD

**Issue by whyman** [pupnp/pupnp#159]
```
config.status: error: in `/app/build/pupnp-release-1.8.6':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
```

With automake 1.16, the release notes indicate they [fixed some kind of bug](https://lists.gnu.org/archive/html/info-gnu/2018-02/msg00008.html).

Not sure what the solution is here...

CMake? :grin:

**Comment by mrjimenez** [comment]
The error message is not really helpful. At all.

I still can't reproduce it here, (automake-1.16.1-5.1.noarch). Though I believe it is just a matter of days or hours...

Do you think cmake would be a better solution? Is it easy to do something like "make dist"?

**Comment by ukleinek** [comment]
In my experience switching the build system just changes one set of problems to another set.

In my bubble (mostly consisting of embedded ARM and Debian stuff) autoconf is the more reliable one, that works better most of the time. (And if a problem arises, there are usually enough people who know enough about autotools to fix it.)

Having said that I don't have an idea off-hand for above problem apart from looking at `config.log`.

**Comment by whyman** [comment]
To clarify, the CMake was (mostly) a joke.

If you pass `--disable-dependency-tracking`   then it seems to work :man_shrugging:

**Comment by mrjimenez** [comment]
> To clarify, the CMake was (mostly) a joke.

Autotools is too. On us. :smile: 

> If you pass `--disable-dependency-tracking` then it seems to work

Good to know, thanks!

**Comment by Vollstrecker** [comment]
I guess this is not a problem anymmore
