### ISSUE TITLE
1.8.4版本无法去除客户端编译

### ISSUE THREAD

**Issue by LancelotWG** [pupnp/pupnp#163]
libupnp-1.8.4版本使用--disable-device的方式去除客户端进行编译，会报编译错误。如需解决需要手动修改预编译的宏控制代码编译内容

**Comment by whyman** [comment]
> 1.8.4 version cannot remove client compilation

> The libupnp-1.8.4 version uses the --disable-device method to remove the client for compilation, and a compilation error will be reported. To solve the need to manually modify the pre-compiled macro control code compilation content

(Thanks google translate!)

**Comment by whyman** [comment]
I suppose its the same issue (#157) fixed in https://github.com/pupnp/pupnp/commit/21f85082e807fda70f254d97e532249e998b1233.

Please try the latest 1.8.x release.

**Comment by mrjimenez** [comment]
Can we close this one?

**Comment by LancelotWG** [comment]
好的
