### ISSUE TITLE
Compile error in list.h using 1.8.4

### ISSUE THREAD

**Issue by jsmith-mygithub** [pupnp/pupnp#168]
Hi, I have an app that links to libupnp v1.8.4 that is compiled on ATOM processor. I get the following error:
list.h:177:35: error: 'UL' undeclared (first use in this function)
entry->next = (struct list_head)LISTPOISON1;

<snip of poison.h>
#ifdef CONFIG_ILLEGAL_POINTER_VALUE
# define POISON_POINTER_DELTA _AC(CONFIGILLEGALPOINTERVALUE, UL)
# else
# define POISON_POINTER_DELTA
#endif
<snip...>

When libupnp is compiled, CONFIG_ILLEGAL_POINTER_VALUE is not defined. But my app has it defined and one of my .c files includes upnp.h, which then generates the above error.

My app uses bitbake to build and we have an automated build system for our daily builds. This means that libupnp is fetched and built. 

Suggested solutions:
1)  Include <linux/const.h> in poison.h
#ifndef _LINUX_POISON_H
#define _LINUX_POISON_H

#ifdef CONFIG_ILLEGAL_POINTER_VALUE
#include <linux/poison.h>
#endif

2)  Add a new file called "const.h" to the libupnp project, base its contents on <linux/const.h> and include this new header in poison.h. The contents of const.h defines the _AC macros.
#ifndef _LINUX_POISON_H
#define _LINUX_POISON_H

#ifdef CONFIG_ILLEGAL_POINTER_VALUE
#include <const.h>
#endif

Let me know if you have any more questions. I have am new to git so I am not sure how to create a patch. This is why I am providing the solutions here.

**Comment by whyman** [comment]
There is an entirely new list implementation in `1.12.0` I suggest you upgrade.

**Comment by jsmith-mygithub** [comment]
I would upgrade, but there is no bitbake file available yet for 1.12.0 in the openembedded project. The latest bitbake file there is for v1.8.4.

Also, to make v1.8.4 fail to compile, just define CONFIG_ILLEGAL_POINTER_VALUE to any value.

**Comment by jsmith-mygithub** [comment]
Hi Ian,

I would like to upgrade to the latest version of libupnp. The project that I am on has many developers working on it simultaneously and uses bitbake to build our application. We are using the latest bitbake recipe from openembedded since our app is related to this area. Openembedded only has v1.8.4.bb file available. If there was a v1.12.bb file, then I would be happy to upgrade.

Is it possible to create a patch for the 1.8.4 branch?

Thanks for the quick response,

Regards,
John

________________________________

**Comment by jsmith-mygithub** [comment]
The patch would look something like this:

Index: libupnp-1.8.4/upnp/inc/poison.h
--- libupnp-1.8.4.orig/upnp/inc/poison.h
+++ libupnp-1.8.4/upnp/inc/poison.h
@@ -2,6 +2,9 @@
 #define _LINUX_POISON_H

 /********** include/linux/list.h **********/
+#ifdef CONFIG_ILLEGAL_POINTER_VALUE
+#include <linux/const.h>
+#endif

 /*
  * Architectures might want to move the poison pointer offset

**Comment by mrjimenez** [comment]
Can we close this one?

**Comment by jsmith-mygithub** [comment]
Yes. sure. I didn't know if I had to close the issue or not.

________________________________
