### ISSUE TITLE
DOC++ is outdated and unsupported

### ISSUE THREAD

**Issue by bocajspear1** [pupnp/pupnp#175]
I tried to build and install DOC++ to build the documentation, but I'm running into multiple issues where I have to manually patch the code to get it to build. DOC++ hasn't been updated since 2002. I know it would take a lot of work and time, but it seems moving to a new documentation system would be recommended. Another possibility could be forking DOC++ and patching it.

**Comment by mrjimenez** [comment]
Hi Jacob,

I think you got that wrong. The library uses Doxygen, not DOC++. They are similar because Doxygen has got a lot of inspiration from DOC++.

You should not get too much trouble installing Doxygen, your distro most certainly has it.

Regards,
Marcelo.

**Comment by bocajspear1** [comment]
Ah, I think I've found the issue. First of all, I'm using an older version (1.8.6, matching the version in buildroot) I should've thought about that and guessed it had been updated since. That's my fault. However, the README still says DOC++:

From the current README:
> Additionally, the documentation for the SDK can be auto-generated from the upnp.h header file using DOC++, a documentation system for C, C++, IDL, and Java\*.  DOC++ generates the documentation in HTML or TeX format. Using some additional tools, the TeX output can be converted into a PDF file. To generate the documentation these tools are required:

> DOC++   | The homepage for DOC++ is <http://docpp.sourceforge.net>. The current version as of this release of the SDK is version 3.4.9. DOC++ is the only requirement for generating the HTML documentation.

So the changes that switch to doxygen are not in the older version, but the current README still says DOC++, which was what I was referencing. Thus, my confusion.

**Comment by mrjimenez** [comment]
Hi Jacob,

Indeed, the documentation is outdated, sorry for that. I have just committed a fix for the README file.

Regards,
Marcelo.

**Comment by bocajspear1** [comment]
Looks good, I'll close this issue
