### ISSUE TITLE
Please consider "Rebase and merge"?

### ISSUE THREAD

**Issue by jbkempf** [pupnp/pupnp#190]
Heya,

Very cool seeing the project advancing quite well, with regular releases.

Anyway, a lot of PR are just one or two commits, and the use of merge commits makes the history quite difficult to follow (and quite ugly).

I would suggest to use more "rebased" merges in those cases.

**Comment by mrjimenez** [comment]
Hi Jean-Baptiste,

You are totally right, I will try to be more careful with that.

Regards,
Marcelo.

**Comment by jbkempf** [comment]
No problem.

**Comment by jbkempf** [comment]
@ePirat

**Comment by whyman** [comment]
There is an option in Github to "require linear history" and there is also a "rebase and merge" option. I am sure you are aware but highlighting if not

**Comment by mrjimenez** [comment]
No, I was not aware of it :)

Thanks a lot!
