### ISSUE TITLE
libupnp-1.12.0 memory leak

### ISSUE THREAD

**Issue by dingmd123** [pupnp/pupnp#191]
How "CLASS##_delete" release the memory which the member of structure pointed ？ 

For example:
UpnpDiscovery *param = UpnpDiscovery_new();
UpnpDiscovery_strncpy_Location(param, hdr_value.buf, hdr_value.length);  // strndup,  will allocate space point to **param->Location. How to release ?**
UpnpDiscovery_delete(param);

void CLASS##_delete(CLASS *q) \
{ \
	struct S##CLASS *p = (struct S##CLASS *)q; \
\
	if (!p) return; \
\
	EXPAND_CLASS_MEMBERS(CLASS) \
\
	free(p); \
}

**Comment by mrjimenez** [comment]
Hi dingmd123,

Please use `UpnpDiscovery_delete(param);` to release the memory associated with the `UpnpDiscovery` object.

You don't need to worry about the memory used by `UpnpDiscovery_strncpy_Location()` because when you delete the `UpnpDiscovery` object, the destructor code will free it.

Please take a look at the master branch. The code is now explicit, we no longer use templates.

Regards,
Marcelo.

**Comment by Vollstrecker** [comment]
Here you forgot to close, too.

**Comment by dingmd123** [comment]
> Here you forgot to close, too.

Thanks for remind. How to closed this issue ?

**Comment by dingmd123** [comment]
> Hi dingmd123,
> 
> Please use `UpnpDiscovery_delete(param)` to release the memory associated with the `UpnpDiscovery` object.
> 
> You don't need to worry about the memory used by `UpnpDiscovery_strncpy_Location()` because when you delete the `UpnpDiscovery` object, the destructor code will free it.
> 
> Please take a look at the master branch. The code is now explicit, we no longer use templates.
> 
> Regards,
> Marcelo.



> Hi dingmd123,
> 
> Please use `UpnpDiscovery_delete(param)` to release the memory associated with the `UpnpDiscovery` object.
> 
> You don't need to worry about the memory used by `UpnpDiscovery_strncpy_Location()` because when you delete the `UpnpDiscovery` object, the destructor code will free it.
> 
> Please take a look at the master branch. The code is now explicit, we no longer use templates.
> 
> Regards,
> Marcelo.

Thanks!

**Comment by mrjimenez** [comment]
You're welcome!
