### ISSUE TITLE
issue in upnpUnregisterClient API

### ISSUE THREAD

**Issue by ashwini-pradeep** [pupnp/pupnp#200]
I am currently using 1.6.25 version of libupnp in our project.I observed that when i switch the network, upnp destructor gets called. It calls upnpUnregisterClient() method in upnpapi.c file.
I have added time logs inside upnpapi.c file. So its taking 2-3 minutes to perform unregistered operation.
And even i called upnpunregisterClient it gives callback like "UPNP_DISCOVERY_ADVERTISEMENT_ALIVE"
All this happening in case of ios environment.
Question:
1. is this normal time needed to unregister operation
2.Is this because ios supports multi threading
3.How to handle it?

**Comment by mrjimenez** [comment]
Hi,

`1.6.25` is an old version of the library, we no longer support it.

My advice is to take a look at the example code `tv_device` and try to reproduce the issue there.

Regards,
Marcelo.

**Comment by Vollstrecker** [comment]
No reaction, old and unsupported version: Closing.
