### ISSUE TITLE
libupnp-1..6.18:socketfd note delted after timeout

### ISSUE THREAD

**Issue by rtsal** [pupnp/pupnp#201]
Hi,
OS: OpenWRT
ibupnp version : 1.6.18

I have a gateway (gw) which runs under linux openwrt,
and I have a windows PC connected to the gw, I am doing tests of adding portmapping by the DeviceSpy tool.
from time to time the DeviceSpy does not manage to add portmapping and it is blocked, and side Gw I noticed "that:
       - a new fd is added under upnpd which points to a socket
            ----------------------------------
> root@mynetwork:~# ls -la /proc/`pidof upnpd`/fd
> dr-x------    2 root     root             0 Jan  1 02:23 
> dr-xr-xr-x    7 root     root             0 Jan  1 02:18 ..
> lrwx------    1 root     root            64 Jan  1 02:23 0 -> /dev/null
> lrwx------    1 root     root            64 Jan  1 02:23 1 -> /dev/null
> lrwx------    1 root     root            64 Jan  1 02:23 10 -> socket:[3379712]
>**lrwx------**    1 root     root            64 Jan  1 02:59 11 -> socket:[3601697]
> lrwx------    1 root     root            64 Jan  1 02:23 2 -> /dev/null
> lrwx------    1 root     root            64 Jan  1 02:23 3 -> socket:[3379704]
> lrwx------    1 root     root            64 Jan  1 02:23 35 -> socket:[4546]
> lrwx------    1 root     root            64 Jan  1 02:23 4 -> socket:[3379706]
> l-wx------    1 root     root            64 Jan  1 02:23 5 -> /IUpnpErrFile.txt
> l-wx------    1 root     root            64 Jan  1 02:23 6 -> /IUpnpInfoFile.txt
> lrwx------    1 root     root            64 Jan  1 02:23 7 -> socket:[3379709]
> lrwx------    1 root     root            64 Jan  1 02:23 8 -> socket:[3379710]
> lrwx------    1 root     root            64 Jan  1 02:23 9 -> socket:[3379711]
> ------------------------------

       - a new socket is opened between upnpd and the DeviceSpy
-----------------------
`
root@mynetwork:~# netstat -npa | grep upnpd
tcp        0      0 192.xx.xx.x:49152       0.0.0.0:*               LISTEN      1895/upnpd
tcp        0      0 192.xx.xx.x:49152       192.168.2.11:60093      ESTABLISHED 1895/upnpd
udp        0      0 127.0.0.1:60444         0.0.0.0:*                           1895/upnpd
udp        0      0 2xx.xx.xx.250:1900    0.0.0.0:*                           1895/upnpd
raw        0      0 0.0.0.0:255             0.0.0.0:*               255         1895/upnpd
unix  3      [ ]         STREAM     CONNECTED     3379704 1895/upnpd  

root@mynetwork:~# grep -rni 3601697 /proc/net/
/proc/net/tcp:20:  18: xxxxxx:C000 0B02A8C0:EABD 01 00000000:00000000 00:00000000 00000000     0        0 3601697 1 cd1eee60 20 4 32 10 16
       
`
-----------------------------------

==> after a little time or after the reboot of GW the socket is closed but the new file descriptor still exists.

**is there a bug?**
**Is there a way to limit the file descriptor because in some cases we get to 1024 file descriptor under the upnpd.
[add_portmapp_ko.txt](https://github.com/pupnp/pupnp/files/5493055/add_portmapp_ko.txt)
**

I enabled debugging and noticed that (see attached file):
   - we remain stuck for a few minutes at the "Trying a write lock" level
  - then we pass "UpnpSendAdvertisement" -> "UpnpSendAdvertisementLowPower"

can you explain it to me?

**Comment by mrjimenez** [comment]
Hi @rtsal ,

Sorry for the late reply.

1.6.18 is a really old (2013-Jan-29) version of the library, we no longer support it. Would it be possible to update it? The last 1.6 release is 1.6.25.

I don't know what is the version that the last version of OpenWRT is using, but maybe it is easier to update OpenWRT itself in you gateway, if that is an option.

Also, if you are able to reproduce it with our sample `tv_device`, maybe we can develop a fix.

Regards,
Marcelo.

**Comment by Vollstrecker** [comment]
As there was no further feedback, openwrt at least doesn't show me any informations about the version, maybe it doesn't provide the lib at all (anymore) and the problem is in an old and not longer supported version, there's no point in keeping this one open.
