### ISSUE TITLE
2 smal thing missed in dcbcc56228

### ISSUE THREAD

**Issue by Vollstrecker** [pupnp/pupnp#204]
Hi,

while your big cleanup you missed 2 little things.

You left the old  upnp/src/genlib/client_table/ClientSubscription.c file after creating the new one.
In  upnp/src/genlib/net/http/httpreadwrite.c You have alloca.h included in line 58, but it's not available under win, so it has to go somewhere under line 69.

I would send an PR for that, but after the rebase, I all my stuff till now would be included.

**Comment by mrjimenez** [comment]
Hi Vollstrecker,

Fixed, thanks!
