### ISSUE TITLE
The library does not work on IPv6 only networks

### ISSUE THREAD

**Issue by ingo-h** [pupnp/pupnp#218]
I'm using a network with only the IPv6 stack enabled (single stack setup). There is no IPv4 stack available or supported. On this network the initialization with `UpnpInit2` always fails with error message:

    UpnpInit2(interface=ens1, port=51515) return code: UPNP_E_INVALID_INTERFACE (-121)

I cloned the current **pupnp** and compiled it. It has this version:

    upnp$ grep UPNP_VERSION_STRING upnp/inc/upnpconfig.h
    #define UPNP_VERSION_STRING "1.14.1"

The test machine is running *Debian Bullseye* but I have the issue also seen on *Debian Buster*. These are the interfaces on the test machine:

    upnp$  ip -brief address
    lo               UNKNOWN        127.0.0.1/8 ::1/128
    ens1             UP             2003:d5:272d:d100:5054:ff:fe40:50f6/64 fe80::5054:ff:fe40:50f6/64

The interface **ens1** works absolutely perfect, e.g.:

    upnp$ ping6 -nc3 google.com
    PING google.com(2a00:1450:4001:80f::200e) 56 data bytes
    64 bytes from 2a00:1450:4001:80f::200e: icmp_seq=1 ttl=118 time=9.67 ms
    64 bytes from 2a00:1450:4001:80f::200e: icmp_seq=2 ttl=118 time=8.39 ms
    64 bytes from 2a00:1450:4001:80f::200e: icmp_seq=3 ttl=118 time=8.38 ms

    --- google.com ping statistics ---
    3 packets transmitted, 3 received, 0% packet loss, time 2004ms
    rtt min/avg/max/mdev = 8.383/8.813/9.669/0.605 ms

    upnp$ curl -6 google.com
    <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
    <TITLE>301 Moved</TITLE></HEAD><BODY>
    <H1>301 Moved</H1>
    The document has moved
    <A HREF="http://www.google.com/">here</A>.
    </BODY></HTML>

To verify that the issue is by **pupnp** I have compiled this tiny test program:

    ~$ cat testipv6.cpp
    #include <stdio.h>
    #include <upnp/upnp.h>
    #include <upnp/upnptools.h>   // UpnpGetErrorMessage
    #include <upnp/upnpdebug.h>   // UpnpSetLogFileNames

    int main()
    {
        constexpr char INTERFACE[] = "ens1";
        unsigned short PORT = 51515;

        constexpr char ErrFileName[]  = "/dev/stderr";
        constexpr char InfoFileName[] = "/dev/stdout";
        int rc;

        UpnpSetLogFileNames(ErrFileName, InfoFileName);

        rc = UpnpInit2(INTERFACE, PORT);
        printf("UpnpInit2(interface=%s, port=%d) return code: %s (%d)\n",
               INTERFACE, PORT, UpnpGetErrorMessage(rc), rc);
    }

It always returns the error message shown above. Can this be fixed, please?

**Comment by mrjimenez** [comment]
Hi Ingo,

I will try to reproduce the problem here. In the mean time, since you compiled the library from the sources, would you re-run your test with a debug enabled library and post the output here?

Regards,
Marcelo.

**Comment by ingo-h** [comment]
@mrjimenez Yes I will do. How to do?

**Comment by mrjimenez** [comment]
When running configure, add `--enable-debug`. The rest of the process is the same.

E.g., I always run the following script so I don't have to think too much:

```bash
./bootstrap && \
./configure --enable-debug --prefix=/home/user/usr/libupnp CFLAGS="-Wall -Wextra -Wpointer-arith -Wwrite-strings -Wformat-security -Wmissing-format-attribute" && \
make clean > /dev/null && \
make > /dev/null && \
make install > /dev/null
```

**Comment by ingo-h** [comment]
@mrjimenez  I dug up the debugger (gdb) and had a session tonight. This is what I found so far:

There is a point `/* Cycle through the list of interfaces looking for IP addresses.  */` (src/api/upnpapi.c:3939). This loop can only check for IPv4 addresses due to the used [struct ifreq](https://man7.org/linux/man-pages/man7/netdevice.7.html) restricted to AF_INET addresses (IPv4). This loop finds only interface "lo" of course, because it is the only one with an IPv4 address 127.0.0.1.

    upnp$ ip -brief address
    lo               UNKNOWN        127.0.0.1/8 ::1/128
    ens1             UP             2003:d5:272d:d100:5054:ff:fe40:50f6/64 fe80::5054:ff:fe40:50f6/64

But as checked by the loop, this is not a valid interface for multicasting in this context. So this loop terminates with `close (LocalSock);` (src/api/upnpapi.c:4012) and returns with `UPNP_E_INVALID_INTERFACE`. That is what we see.

The next part of the program after the IPv4 loop where IPv6 addresses are checked is never reached. You have to ensure that to fix the bug. Because I'm stuck with my project it would be nice if you can publish a patch :-)

**Comment by ffontaine** [comment]
Indeed, back at the time this code was written, the [UPnP Device Architecture](https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf) required a dual-stack device:

> UDA  1.0  devices  and control points SHALL implement IPv4 and support IPv4-only operation, and  SHOULD  implement  IPv6  and  support  dual  stack  (IPv4  and  IPv6)  operation.    Vendors MAY  choose  to  allow  IPv6-only  operation  as  a  policy  alternative,  but  a  device  and  a  control  point SHALL run IPv4 in order to be certified.

However, the UDA was updated in 2020 and now mentions:

> UDA 2.0  devices  and  control  points  SHALL  implement  IPv4  and  IPv6,  SHALL  support  dual  stack (IPv4 and IPv6) operation, and SHALL be capable of operating on IPv4-only and IPv6-only   networks. Vendors   MAY   choose   to   allow   IPv4-only   and/or   IPv6-only   operation   as   configuration  alternatives,  but  a  device  and  a  control  point  SHALL  run  dual-stack  in  order  to  be certified.

The easiest way of fixing this issue would be to simplify the code and assume that `getifaddrs` is always available even if is not POSIX compliant. I'll send a PR so you can test it.

**Comment by mrjimenez** [comment]
I have accepted Fabrice's pull request. Ingo, would you please test the newest version of the repository? If all is ok, I think it justifies a new release.

Regards,
Marcelo.

**Comment by ingo-h** [comment]
Does not work.  
My [simple testprogram](https://github.com/pupnp/pupnp/issues/218#issue-799216347) now returns:

    UpnpInit2(interface=ens1, port=51515) return code: UPNP_E_SOCKET_ERROR (-208)

I will have a look at it. Shouldn't the issue be reopened?

**Comment by mrjimenez** [comment]
Sure, in fact it should not have been closed until you say it is ok. Github may close stuff automatically depending on how you write things.

But now you do have some debug messages to post to us, don't you?

**Comment by ingo-h** [comment]
I'm not clear. I already get `/* Set the UpnpSdkInit flag to 1 to indicate we're successfully initialized. */` with `UpnpSdkInit = 1;`, but the next and last step is to call `UpnpInitStartServers` and that fails with the shown error. (src/api//upnpapi.c:526). May be an issue with my environment? I'm working on it.

**Comment by mrjimenez** [comment]
Hi Ingo,

If you are linking against a debug enabled library, you should have a debug log with lots of messages. The failing point should be there. If you want to figure it out by yourself, thats ok, but don't let us curious to long! :smiley:

**Comment by ingo-h** [comment]
OK, I have found that it is a bug also resulting from the assumption that there always is an IPv4 address available. As already told in the previous comment, the sdk is successfully initialzed and `UpnpInitStartServers` is called without checking the availability of an IPv4 address (src/api//upnpapi.c:526). This results to a registration with `setsockopt` to a multicast group `250.255.255.239` with interface address `0` which fails with `UPNP_E_SOCKET_ERROR` (src/ssdp/ssdp_server.c:994).

To fix it, this function should not be called if no IPv4 address is available and must continue to check for IPv6 addresses.

**Comment by ingo-h** [comment]
Hello Marcello,

about the debug log: yes I saw them all over the source and had a brief look at journalctl, `var/log` and searched for '*debug*` and `*log*`, with no avail. But no problem so far for me because I haven't done software programming for some time and I would like to refresh my debugging skills and to have a look at the source. But I will first have a look at the log now. Where to look?

Btw.: I prefer to use unit tests instead of the debugger. Are there any unit tests for the library?

**Comment by mrjimenez** [comment]
Hi Ingo,

Unfortunately, there are very few unit tests in the library, increasing the number of tests would be really cool.

The logs are not in journalctl, they go to an user specified log file. In your test program, make a call to UpnpSetLogFileNames(). Please take a look at `upnp/src/api/upnpdebug.c`. There is an example in `upnp/test/test_log.c`. BTW, the unit tests are located in `upnp/test` and they run in the github actions, but also if you do `make check`.

**Comment by ingo-h** [comment]
I have logging enabled now. Here is what I get:

    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:378]: Inside UpnpInitPreamble
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:394]: Trying a write lock
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:394]: Write lock acquired
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:398]: Trying Unlock
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:398]: Unlocked rwlock
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:510]: UpnpInit2 with IfName=ens1, DestPort=51515.
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:3885]: Interface name=ens1, index=2, v4=0.0.0.0, v6=fe80::
    5054:ff:fe40:50f6, ULA or GUA v6=2003:d5:272d:d100:5054:ff:fe40:50f6
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:448]: Entering UpnpInitStartServers
    2021-02-08 14:50:52 UPNP-MSER-2: Thread:0x7FD2EE7CEB80 [src/genlib/miniserver/miniserver.c:557]: sockfd = 4, .... port = 51515
    2021-02-08 14:50:52 UPNP-MSER-2: Thread:0x7FD2EE7CEB80 [src/genlib/miniserver/miniserver.c:557]: sockfd = 5, .... port = 51515
    2021-02-08 14:50:52 UPNP-MSER-2: Thread:0x7FD2EE7CEB80 [src/genlib/miniserver/miniserver.c:557]: sockfd = 6, .... port = 51515
    2021-02-08 14:50:52 UPNP-MSER-2: Thread:0x7FD2EE7CEB80 [src/genlib/miniserver/miniserver.c:900]: get_miniserver_sockets: bind succes
    sful
    2021-02-08 14:50:52 UPNP-MSER-2: Thread:0x7FD2EE7CEB80 [src/genlib/miniserver/miniserver.c:557]: sockfd = 7, .... port = 35038
    2021-02-08 14:50:52 UPNP-SSDP-0: Thread:0x7FD2EE7CEB80 [src/ssdp/ssdp_server.c:1004]: Error in setsockopt() IP_ADD_MEMBERSHIP (join
    multicast group): No such device
    2021-02-08 14:50:52 UPNP-API_-0: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:461]: Miniserver failed to start
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:633]: Inside UpnpFinish: UpnpSdkInit is 1
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:640]: UpnpFinish: UpnpSdkInit is ONE
    2021-02-08 14:50:52 UPNP-API_-2: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:643]: Send Thread Pool
    --- snip ---
    (a bunch of timing info and GetHandleInfos)

**Comment by ingo-h** [comment]
With the test suite `make check` I get the same output in `upnp/test-suite.log` as shown above. Is there any information about the test suite? Does it support mocking?

**Comment by mrjimenez** [comment]
As far as I understand, this is not a sophisticated unit test framework like modern javascript. This uses very old stuff in autotools, but I have not looked into the documentation for its capabilities.

This is the code inside Makefile.am:

```Makefile
# check / distcheck tests
check_PROGRAMS = test_init test_url test_log test_list
TESTS = test_init test_url test_log test_list
test_init_SOURCES = test/test_init.c
test_url_SOURCES = test/test_url.c
test_log_SOURCES = test/test_log.c
test_list_SOURCES = test/test_list.c
```

This is basically a bunch of test programs in the `test` subdirectory that return 0 (EXIT_SUCCESS) when all went ok and 1 (EXIT_FAILURE) in case things go bad. I do encourage you to add your test code to this folder as a PR, since it is definitely catching a problem, so that when all is fixed, we are not going to have a regression.

For inspiration, there are two samples that can be used to build a primitive mocking system, a device sample and a control point sample. There is also a combo sample (device + control point), that is basically the two previous ones combined into a single executable, which may be even more useful from a unit test point of view.

**Comment by mrjimenez** [comment]
BTW, the problem is here:
```
2021-02-08 14:50:52 UPNP-SSDP-0: Thread:0x7FD2EE7CEB80 [src/ssdp/ssdp_server.c:1004]: Error in setsockopt() IP_ADD_MEMBERSHIP (join multicast group): No such device
2021-02-08 14:50:52 UPNP-API_-0: Thread:0x7FD2EE7CEB80 [src/api/upnpapi.c:461]: Miniserver failed to start
```

See the code below:

```c
	memset((void *)&ssdpMcastAddr, 0, sizeof(struct ip_mreq));
	ssdpMcastAddr.imr_interface.s_addr = inet_addr(gIF_IPV4);
	ssdpMcastAddr.imr_multiaddr.s_addr = inet_addr(SSDP_IP);
	ret = setsockopt(*ssdpSock,
		IPPROTO_IP,
		IP_ADD_MEMBERSHIP,
		(char *)&ssdpMcastAddr,
		sizeof(struct ip_mreq));
	if (ret == -1) {
		strerror_r(errno, errorBuffer, ERROR_BUFFER_LEN);
		UpnpPrintf(UPNP_CRITICAL,
			SSDP,
			__FILE__,
			__LINE__,
			"Error in setsockopt() IP_ADD_MEMBERSHIP (join "
			"multicast group): %s\n",
			errorBuffer);
		ret = UPNP_E_SOCKET_ERROR;
		goto error_handler;
	}
```

It assumes that missing IPV4 is an error, which as we have previously discussed, is a wrong assumption.

**Comment by ffontaine** [comment]
https://github.com/pupnp/pupnp/pull/226 should hopefully fix the issue.

**Comment by mrjimenez** [comment]
Hi Ingo,

Is this still an issue after Fabrice's #226? If not, please close it.

Regards,
Marcelo.

**Comment by ingo-h** [comment]
Hi @mrjimenez,

I will look, but just busy with gtests for win32.

**Comment by Vollstrecker** [comment]
@ingo-h Did you have the time to check if the issue persists?

**Comment by ingo-h** [comment]
Have overseen this issue ... will look at it this days.

**Comment by ingo-h** [comment]
I use the latest commit a9bbb0cdd61a6b45a9288ec899f25f268086c98f from the master branch on a system having only one ipv6 interface:

    : lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
        inet6 ::1/128 scope host
           valid_lft forever preferred_lft forever
    2: ens1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 52:54:00:40:50:f6 brd ff:ff:ff:ff:ff:ff
        altname enp8s1
        inet6 2003:d5:273d:b800:5054:ff:fe40:50f6/64 scope global dynamic mngtmpaddr noprefixroute
           valid_lft 7057sec preferred_lft 1057sec
        inet6 fe80::5054:ff:fe40:50f6/64 scope link
           valid_lft forever preferred_lft forever

Update the tiny test program and use it on the projects root directory (CMAKE_SOURCE_DIR):

    ~$ cat testipv6.cpp
    #include <stdio.h>
    #include "upnp.h"
    #include "upnptools.h"   // UpnpGetErrorMessage
    #include "UpnpLog.h"     // UpnpSetLogFileName

    int main()
    {
        constexpr char INTERFACE[] = "ens1";
        unsigned short PORT = 51515;
        UpnpLib* p{};

        int rc = UpnpInit2(&p, INTERFACE, PORT, "/dev/stdout");
        printf("UpnpInit2(interface=%s, port=%d) return code: %s (%d)\n",
               INTERFACE, PORT, UpnpGetErrorMessage(rc), rc);
    }

Then I build and compile it with:

    ~$ cmake -S . -B build
    ~$ cmake --build build
    ~$ g++ -pedantic-errors -Wall -I./upnp/inc/ -I./build/upnp/inc/ -I./ixml/inc/ -otestipv6 testipv6.cpp build/upnp/libupnp.a build/ixml/libixml.a -lpthread

The resulting program executed with:

    ~$ ./testipv6
    UpnpInit2(interface=ens1, port=51515) return code: UPNP_E_SUCCESS (0)

Works. So I close this issue.
