### ISSUE TITLE
Using a test environment for Unit Tests

### ISSUE THREAD

**Issue by ingo-h** [pupnp/pupnp#225]
Instead of debugging for bug fixes I prefer to use Unit Tests.

About the available tests @mrjimenez wrote at ttps://github.com/pupnp/pupnp/issues/218#issuecomment-775214410
>As far as I understand, this is not a sophisticated unit test framework like modern javascript. This uses very old stuff in autotools, but I have not looked into the documentation for its capabilities.

I like [googletest](https://github.com/google/googletest) and will try it local on my cloned pupnp. Is there any chance to get it integrated into this project? Or are other test environments preferred? Because with multicasting we have hard to emulate I/O functions, I think that the test environment must support mocking.

**Comment by mrjimenez** [comment]
Definitely do it. If you make it work as you intend, it will be integrated. The way I see, it is a welcome addition and does not interfere with the current primitive unit testing.

**Comment by ingo-h** [comment]
I'm a bit unsure because the environment is using C++, but of course it can also test pure C programs [Unit Testing C Code](https://stackoverflow.com/a/1410143/5014688).

**Comment by Vollstrecker** [comment]
If I see that correct, you can define expected return values, like success is expected now. Or you can emulate (some kind of) library calls for the libs in the source. The problem seems to be the call of a system-library. Maybe I'm wrong, but I didn't see this in the docs.

I don't understand this appraoch at all so I'm curious what benefit comes from that. At least I (with my limited knwoledge of that) can't imagine a real benefit, just a replacement, maybe better readable but nothing that would legitimate a new dep. So just surprise me.

Btw. I'll add that to CmDaB tommorow, as they describe an old technic for the on-the-fly-download, so you'll just need one command instead of the 20+ the listed.

**Comment by ingo-h** [comment]
Hi @Vollstrecker, I'm just starting with all of this. I'm interested in multicasting/upnp on an IPv6 only network because of a project I'm following. In particular I'm looking at the current bug at [The library does not work on IPv6 only networks](https://github.com/pupnp/pupnp/issues/218) and try to understand the library. I'm afraid this will not be the only bug with supporting IPv6, because it seems that on the whole library is assumed that IPv4 is always available. I had a look at the available tests but could not find any useful information to understand how they work. Because I have already used *googletest* so it is obvious for me to try it on my local clone. After some unit tests I think we will have a better basis for comparison. At this time I can't say much about it.

The bug we have found is described at https://github.com/pupnp/pupnp/issues/218#issuecomment-775221208. There the system call *setsockopt* is failing. How would you test all calling functions?

**Comment by Vollstrecker** [comment]
I don't know that much more about lib as you do, I'm just working in the periphery. If that are not so much external calls, you could just call them, as the tests and the samples do. I think that is what Marcello did. He knows the lib best, so if think's it's a good idea, just go for it. I (more or less) always available to support you with that.

The problems with tests is always, that you have to know what to test, and what to expect. If you know that, it just doesn't matter what you use.

**Comment by ingo-h** [comment]
I try to setup **googletest** to be available in **pupnp** as described at [Incorporating Into An Existing CMake Project](https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project). There is given a `CMakeLists.txt` but there is already a `pupnp/CMakeLists.txt`. I'm not familiar with `CMake`.

Does anybody know how to correctly configure it?

**Comment by Vollstrecker** [comment]
As I said, their description isn't that good.

For just getting it useable you can set DOWNLOAD_AND_BUILD_DEPS=TRUE, and then anywhere after line 4 you can add:

`if (DOWNLOAD_AND_BUILD_DEPS)`
`    CmDaB_install (googletest)`
`endif()`

Then you should be able to use it. This doesn't check for any existing installation or whatever at all, but for getting your tests done it should be good enough.

**Comment by ingo-h** [comment]
I got it going. Of course, the installation is a bit quick and dirty at time and needs some improvement. But here is the same test of **UpnpInit2** as shown at https://github.com/pupnp/pupnp/issues/218#issue-799216347 but under test conditions.

    gtest$ cat test_initialization.cpp
    #include "gtest/gtest.h"
    #include "upnp.h"

    TEST(PupnpInitTestSuite, initialization)
    {
        constexpr char INTERFACE[] = "ens1";
        unsigned short PORT = 51515;

        EXPECT_EQ(UpnpInit2(INTERFACE, PORT), UPNP_E_SUCCESS);
    }

    int main(int argc, char **argv) {
      ::testing::InitGoogleTest(&argc, argv);
      return RUN_ALL_TESTS();

Of course it fails because it does not return UPNP_E_SUCCESS:

    [==========] Running 1 test from 1 test suite.
    [----------] Global test environment set-up.
    [----------] 1 test from PupnpInitTestSuite
    [ RUN      ] PupnpInitTestSuite.initialization
    test_initialization.cpp:9: Failure
    Expected equality of these values:
      UpnpInit2(INTERFACE, PORT)
        Which is: -208
      0
    [  FAILED  ] PupnpInitTestSuite.initialization (2 ms)
    [----------] 1 test from PupnpInitTestSuite (2 ms total)

    [----------] Global test environment tear-down
    [==========] 1 test from 1 test suite ran. (4 ms total)
    [  PASSED  ] 0 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] PupnpInitTestSuite.initialization

     1 FAILED TEST

I will improve the tests with the goal to fix the bug with same behavior of the library.

**Comment by ingo-h** [comment]
I did some more tests to verify that googletest, using C++ objects, can run the C library under test conditions. It is said, that the C++ compiler can also compile pure C programs but it is also said that this can have some side effects. This is also true with pupnp. But it is no problem to compile the library at usual with GCC and test against the static library. This also ensures that a main requirement of unit tests is met: the production code must remain unchanged for testing.

I have now 5 tests running on two functions from the upnpapi module with an IPv4 and IPv6 interface UP and the benefit is already very great. These interfaces are UP:

    gtest$ ip -br addr
    lo               UNKNOWN        127.0.0.1/8 ::1/128
    ens1             UP             2003:d5:2721:900:5054:ff:fe40:50f6/64 fe80::5054:ff:fe40:50f6/64
    ens2             UP             192.168.24.130/16

 Here is the test result:

    gtest$ ./test_upnpapi.a
    [==========] Running 5 tests from 3 test suites.
    [----------] Global test environment set-up.
    [----------] 2 tests from UpnpApiIPv4TestSuite
    [ RUN      ] UpnpApiIPv4TestSuite.UpnpGetIfInfo
    [       OK ] UpnpApiIPv4TestSuite.UpnpGetIfInfo (1 ms)
    [ RUN      ] UpnpApiIPv4TestSuite.UpnpInit2
    [       OK ] UpnpApiIPv4TestSuite.UpnpInit2 (54 ms)
    [----------] 2 tests from UpnpApiIPv4TestSuite (59 ms total)

    [----------] 2 tests from UpnpApiIPv6TestSuite
    [ RUN      ] UpnpApiIPv6TestSuite.UpnpGetIfInfo
    test_upnpapi.cpp:75: Failure
    Expected equality of these values:
      gIF_NAME
        Which is: "ens2"
      interface.c_str()
        Which is: "ens1"
    test_upnpapi.cpp:76: Failure
    Expected equality of these values:
      gIF_IPV4
        Which is: "192.168.24.130"
      ""
    test_upnpapi.cpp:78: Failure
    Value of: gIF_IPV6
    Expected: matches regular expression "([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4}"
      Actual: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" (of type char [46])
    test_upnpapi.cpp:79: Failure
    Value of: gIF_IPV6_ULA_GUA
    Expected: matches regular expression "([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4}"
      Actual: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" (of type char [46])
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpGetIfInfo (3 ms)
    [ RUN      ] UpnpApiIPv6TestSuite.UpnpInit2
    test_upnpapi.cpp:87: Failure
    Expected equality of these values:
      return_value
        Which is: -105
      0
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpInit2 (0 ms)
    [----------] 2 tests from UpnpApiIPv6TestSuite (3 ms total)

    [----------] 1 test from UpnpApiTestSuite
    [ RUN      ] UpnpApiTestSuite.GetHandleInfo
    [       OK ] UpnpApiTestSuite.GetHandleInfo (0 ms)
    [----------] 1 test from UpnpApiTestSuite (0 ms total)

    [----------] Global test environment tear-down
    [==========] 5 tests from 3 test suites ran. (68 ms total)
    [  PASSED  ] 3 tests.
    [  FAILED  ] 2 tests, listed below:
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpGetIfInfo
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpInit2

     2 FAILED TESTS

These tests are against the **UpnpGetIfInfo** and the **UpnpInit2** functions. It shows that the UpnpApiIPv4TestSuite is running without failour, as expected.

The UpnpApiIPv6TestSuite fails.

 * UpnpGetIfInfo sets the wrong interface. It must set gIF_NAME to **ens1** instead of **ens2**.
 * gIF_IPV4 is set to "192.168.24.130". I have expected it to be "". But this is opinion based and can be discussed.
 * gIF_IPV6 does not contain the IPv6 address. It is still empty.
 * With the wrong interface info UpnpInit2 returns -105 of course, which is defined as UPNP_E_INIT.

These tests are only for two interfaces up. They will give wrong information for the other remaining three conditions (no if up, only IPv4 up, only IPv6 up). But with a try with only IPv6 up I found that UpnpInit2 hangs and never return:

    gtest$ sudo ip link set dev ens2 down
    gtest$ ip -br addr
    lo               UNKNOWN        127.0.0.1/8 ::1/128
    ens1             UP             2003:d5:2721:900:5054:ff:fe40:50f6/64 fe80::5054:ff:fe40:50f6/64
    ens2             DOWN

    gtest$ time ./test_upnpapi.a
    [==========] Running 5 tests from 3 test suites.
    --- snip ---
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpGetIfInfo (1 ms)
    [ RUN      ] UpnpApiIPv6TestSuite.UpnpInit2
    ^C

    real    1m33,888s
    user    0m0,006s
    sys     0m0,007s

UpnpInit2 will never return. I canceled the test with Ctrl+C after 1m33,888s.

I suggest to do not take effort at this time to fix the bugs. I will make a break with creating additional tests and will provide an installation of googletest with `cmake` and the current test environment so that it is possible to work with it together if desired.

The test environment can be installed with a `cmake` option and does not effect the default installation without the option.

The next step then I will try is to get mocking to run. This is a very important feature that makes us independent from the physical presence of network interfaces. This is not an easy task with testing a C library because it doesn't support virtual interfaces for objects.

**Comment by ingo-h** [comment]
I have just updated my local clone with the latest commits on the github master. Sorry for the delay. The tests look much better now.

For an IPv6 interface **gIF_IPV4** still contains an ip address, But as already said, that's opinion based. Shouldn't it set to an empty string? We are looking for an IPv6 address.

The other failures from **UpnpGetIfInfo** for an IPv6 ip address are removed now but **UpnpInit2** still fails with return_value -105 (UPNP_E_INIT). We need some more tests.

With only an IPv6 interface UP, **UpnpInit2** does not hang anymore. It returns now after 91 ms total.

Good job so far :-)

    gtest$ ./test_upnpapi.a
    [==========] Running 5 tests from 3 test suites.
    [----------] Global test environment set-up.
    [----------] 2 tests from UpnpApiIPv4TestSuite
    [ RUN      ] UpnpApiIPv4TestSuite.UpnpGetIfInfo
    [       OK ] UpnpApiIPv4TestSuite.UpnpGetIfInfo (1 ms)
    [ RUN      ] UpnpApiIPv4TestSuite.UpnpInit2
    [       OK ] UpnpApiIPv4TestSuite.UpnpInit2 (2 ms)
    [----------] 2 tests from UpnpApiIPv4TestSuite (3 ms total)

    [----------] 2 tests from UpnpApiIPv6TestSuite
    [ RUN      ] UpnpApiIPv6TestSuite.UpnpGetIfInfo
    test_upnpapi.cpp:76: Failure
    Expected equality of these values:
      gIF_IPV4
        Which is: "192.168.24.130"
      ""
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpGetIfInfo (1 ms)
    [ RUN      ] UpnpApiIPv6TestSuite.UpnpInit2
    test_upnpapi.cpp:87: Failure
    Expected equality of these values:
      return_value
        Which is: -105
      0
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpInit2 (0 ms)
    [----------] 2 tests from UpnpApiIPv6TestSuite (1 ms total)

    [----------] 1 test from UpnpApiTestSuite
    [ RUN      ] UpnpApiTestSuite.GetHandleInfo
    [       OK ] UpnpApiTestSuite.GetHandleInfo (0 ms)
    [----------] 1 test from UpnpApiTestSuite (0 ms total)

    [----------] Global test environment tear-down
    [==========] 5 tests from 3 test suites ran. (5 ms total)
    [  PASSED  ] 3 tests.
    [  FAILED  ] 2 tests, listed below:
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpGetIfInfo
    [  FAILED  ] UpnpApiIPv6TestSuite.UpnpInit2

     2 FAILED TESTS

**Comment by ingo-h** [comment]
Googletest and Googlemock are merged into the master. Unit testing is going on now.
