### ISSUE TITLE
Wrong pupnp soname/library version with cmake

### ISSUE THREAD

**Issue by marillat** [pupnp/pupnp#231]
Until now the libupnp soname was set to libupnp.so.17 and library name to libupnp.so.17.0.1
When pupnp is built with cmake the soname is set to libupnp.so.1 and library name to libupnp.so.1.14.1

I think it is a bug.

**Comment by marillat** [comment]
Thanks for the patch, but the library name is **libupnp** not **libpupnp** except if the first name was broken until now.

**Comment by Vollstrecker** [comment]
It is, compare #224. I changed it back until the final decision was made.
I didn't know this change was already in my changeset, but that explains why there haven't been errors like I expected.
