### ISSUE TITLE
[1.12.1]When XML files containing many subnodes are used in SOAP messages, services are unavailable.

### ISSUE THREAD

**Issue by KelsonHoole** [pupnp/pupnp#236]
I used an XML message containing many subnodes in the request and tried to send it to the DLNA server. Then I found that the memory of the process processing the message was increasing, the CPU usage did not recover, and the service was suspended.

eg:

POST /upnp/service/RenderingControl/Control HTTP/1.1

<?xml version="1.0" encoding="utf-8"?>
<tns:Envelope xmlns:tns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1" tns:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <tns:Body>
    <u:GetMute>
        <InstanceID>0</InstanceID>
        <Channel>Master</Channel>
    </u:GetMute>

    <u:GetMute>
        <InstanceID>0</InstanceID>
        <Channel>Master</Channel>
    </u:GetMute>

    <u:GetMute>
        <InstanceID>0</InstanceID>
        <Channel>Master</Channel>
    </u:GetMute>

    <u:GetMute>
        <InstanceID>0</InstanceID>
        <Channel>Master</Channel>
    </u:GetMute>

......

**Comment by xzjpgithub** [comment]
大兄弟，需要描述的详细点，你这样没人回啊...

**Comment by mrjimenez** [comment]
@xzjpgithub , @hukecn is not getting a reply because it is not clear what the setup is, how we can reproduce, what the expected behavior should be and what he wants. We need more details.

Also, please avoid using Chinese in the forum. English is not my native language too.

Regards,
Marcelo.
