### ISSUE TITLE
[1.14.1] Segfault when attempting to browse upnp in VLC

### ISSUE THREAD

**Issue by tmn505** [pupnp/pupnp#237]
Description:
Segfaults when prompted to search for upnp servers after recent update. Works fine with libupnp-1.14.0.

Bisection of the git pointed to first bad commit:
aa0166c9a87a6f02632a0c55fb6174b6a1bf8289  upnpapi.c: assume that getifaddrs is available
The issue seems to be fixed in HEAD, the first good commit:
066c4ed35518b9cfc4c156649d032e24029ac0ec  Handle interfaces without address

Additional info: 
Arch Linux and vlc-3.0.12

Steps to reproduce:

    Install on an up to date system.
    Open VLC
    Click "Universal Plug'n'Play" in "Local Network"
    Segfaults

Stack trace attached for segfault with 1.14.1
[vlc-stack-trace.txt](https://github.com/pupnp/pupnp/files/6029344/vlc-stack-trace.txt)

**Comment by mrjimenez** [comment]
Hi @tmn505 , this problem should have been fixed by these patches: #234 #235 that will be in 1.14.2.

Should we close this issue or do you want to teste it?

**Comment by tmn505** [comment]
Thanks and yes, it's fixed in that branch.
