### ISSUE TITLE
Get the library and server to create handles

### ISSUE THREAD

**Issue by wooky** [pupnp/pupnp#241]
Functions such as UpnpInit2, UpnpSetWebServerRootDir, etc. operate on some internal, global handle. I think it would be better if (some variation of) these functions would return a handle, so other functions like registering a device would be done on specific handles.

Use cases could include:
- Starting the library without starting the internal server, and not having to worry about which interface and port to use
- Initializing multiple web servers and adding devices, virtual directories, etc. to individual server

**Comment by whyman** [comment]
Agreed this would be useful.

The reality is that you would have to put together these changes yourself, but I am sure that they would be gladly received.

**Comment by whyman** [comment]
It is also no means trivial, there is a boat load of global state.

**Comment by mrjimenez** [comment]
Folks, please take a look at #255.

**Comment by mrjimenez** [comment]
Can we close this issue? It has already been implemented.

**Comment by Vollstrecker** [comment]
Doesn't this question answer itself?

**Comment by mrjimenez** [comment]
The last time I did something like this I got complaints :smile:

**Comment by Vollstrecker** [comment]
No complains for 8 month now and it's implemented. Everything that could come up now would be a new issue - closing.

**Comment by whyman** [comment]
There hasnt actually been a release with this code in yet, though.

**Comment by Vollstrecker** [comment]
That's right, but not the point. If there no problems with the code this will be in the release when master get's a new version. The issues are always fixed with the commit not the release. Admitted, the release will not be short after the fix in this case.
