### ISSUE TITLE
master branch does not compile

### ISSUE THREAD

**Issue by ingo-h** [pupnp/pupnp#259]
I just pulled the latest changes from the master branch but it doesn't compile anymore. I get this error:

    pupnp $ cmake . -DDOWNLOAD_AND_BUILD_DEPS=ON -DBUILD_TESTING=ON
    pupnp $ make
    --- snip ---
    Scanning dependencies of target tv_device
    [ 92%] Building C object upnp/sample/CMakeFiles/tv_device.dir/common/sample_util.c.o
    [ 93%] Building C object upnp/sample/CMakeFiles/tv_device.dir/common/tv_device.c.o
    /home/ingo/devel/pupnp-dev/pupnp/upnp/sample/common/tv_device.c:1519:5: error: conflicting types for ‘device_main’
     1519 | int device_main(int argc, char *argv[], int combo)
          |     ^~~~~~~~~~~
    In file included from /home/ingo/devel/pupnp-dev/pupnp/upnp/sample/common/tv_device.c:44:
    /home/ingo/devel/pupnp-dev/pupnp/upnp/sample/common/tv_device.h:569:5: note: previous declaration of ‘device_main’ was here
      569 | int device_main(int argc, char *argv[]);
          |     ^~~~~~~~~~~
    make[2]: *** [upnp/sample/CMakeFiles/tv_device.dir/build.make:95: upnp/sample/CMakeFiles/tv_device.dir/common/tv_device.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:882: upnp/sample/CMakeFiles/tv_device.dir/all] Error 2
    make: *** [Makefile:160: all] Error 2

**Comment by mrjimenez** [comment]
Hi @ingo-h , sorry for that. I have left one file out of the last commit.

Should be fixed now.

**Comment by ingo-h** [comment]
Thanks, its compiling now.
