### ISSUE TITLE
CMakeLists.txt missing in official 1.14.1 and 1.14.2 tarballs

### ISSUE THREAD

**Issue by ffontaine** [pupnp/pupnp#280]
`CMakeLists.txt` is not in the official [1.14.2 tarball](https://github.com/pupnp/pupnp/releases/download/release-1.14.2/libupnp-1.14.2.tar.bz2) despite being in github: https://github.com/pupnp/pupnp/blob/release-1.14.2/CMakeLists.txt.

There is the same issue with 1.14.1.

**Comment by ffontaine** [comment]
Thanks, I'll try 1.14.3 with buildroot.

**Comment by ffontaine** [comment]
Unfortunately, it seems that some files are missing in the tarball:

```
CMake Error: File /home/fabrice/buildroot/output/build/libupnp-1.14.3/upnp/inc/upnpconfig.h.cm does not exist.
CMake Error at CMakeLists.txt:414 (configure_file):
  configure_file Problem configuring file


CMake Error: File /home/fabrice/buildroot/output/build/libupnp-1.14.3/upnp/sample/common/config_sample.h.cm does not exist.
CMake Error at CMakeLists.txt:415 (configure_file):
  configure_file Problem configuring file
```

**Comment by mrjimenez** [comment]
Try it now.
