### ISSUE TITLE
release-1.14.9 did not get release properly

### ISSUE THREAD

**Issue by chenrui333** [pupnp/pupnp#338]
👋  just a heads up, it looks like the 1.14.9 release did not get fully done (like the tag is not marked as `latest release` and some release artifacts did not get attached). Thanks!

cc @mrjimenez

**Comment by mrjimenez** [comment]
Hi Rui,

1.14.9 has problems, we will skip it. Just waiting for a requested patch review to make a new release.

Thanks!
Marcelo.

**Comment by mrjimenez** [comment]
Hi Rui,

1.14.10 has been released, can we close this issue?

**Comment by Vollstrecker** [comment]
Not an Issue (anymore), closing.
