### ISSUE TITLE
pull Feb 14, 2022, but tv_device not working

### ISSUE THREAD

**Issue by powerpun** [pupnp/pupnp#378]
./tv_device -i wlan1 -port 5324 -webdir /work/pupnp-master/upnp/sample/web -desc tvdevicedesc.xml -m 1
Initializing UPnP Sdk with
        interface = wlan1 port = 5324
UPnP Initialized
        ipaddress = 192.168.18.79 port = 5324
Specifying the webserver root directory -- /work/pupnp-master/upnp/sample/web
Registering the RootDevice
         with desc_doc_url: http://192.168.18.79:5324/tvdevicedesc.xml
Segmentation fault

anything I did wrong ?

**Comment by whyman** [comment]
Did you use cmake or autotools? Can you tell us about your OS/Arch?

**Comment by Vollstrecker** [comment]
And more interesting, is it working in 1.14, as master is a dead horse that shouldn't be ridden.

**Comment by powerpun** [comment]
> Did you use cmake or autotools? Can you tell us about your OS/Arch?

Debian stretch. arm 7, local compile with on board tool chain. follow compile instruction exactly, and built the samples.

**Comment by powerpun** [comment]
just wanna know who could build this, need working compile direction.. thanks

**Comment by mrjimenez** [comment]
Hi @powerpun ,

We need to know which library version you are using. What @Vollstrecker means is that currently the master branch is broken, so you should try to use 1.14.9, which is the latest stable version. Also, what @whyman means is that there are currently two ways of building the library, you can either use autotools or CMake.

Regards,
Marcelo.

**Comment by powerpun** [comment]
got
