### ISSUE TITLE
UpnpExtraHeaders.h missing from cmake build in branch-1.14x

### ISSUE THREAD

**Issue by kyak** [pupnp/pupnp#384]
UpnpExtraHeaders.h is missing when doing cmake build in branch-1.14x. This leads to errors when building downstream software, like gerbera: https://github.com/gerbera/gerbera/issues/2506

**Comment by Vollstrecker** [comment]
Compare: https://github.com/pupnp/pupnp/commit/124046339933c7310918e9d4c28051cef9079a9f

**Comment by kyak** [comment]
> Compare: [1240463](https://github.com/pupnp/pupnp/commit/124046339933c7310918e9d4c28051cef9079a9f)

I frankly have no idea what you mean by this.

**Comment by neheb** [comment]
He's pointing out why this bug was introduced.

**Comment by Vollstrecker** [comment]
Yep, but it seems this never made it into 1.14.x, so my bad.

**Comment by whyman** [comment]
It can't be renamed in stable right?

**Comment by Vollstrecker** [comment]
It could, but this would mean a versioncheck and conditional for your include. Given between 1.14.x and 1.16.x this would be also needed but this is a new release, on bugfixbranches I would avoid such changes. From my personal feelings such thing belong into major releases, but 1.14 to 1.16 (why not 1.15?) feels like a major one in this project, especially as major means breaking features and by now no features for a new release at all are on their way.
