### ISSUE TITLE
JobPool too small

### ISSUE THREAD

**Issue by KarlStraussberger** [pupnp/pupnp#449]
Can we somehow allow increasing the pool size from 100 to say 500. I suppose that since we are hosting all web requests internally the number of allowed pending requests may be too small now.

https://github.com/gerbera/gerbera/issues/3236

**Comment by mrjimenez** [comment]
Sure, can you place a patch?

I know I still owe you a release, I was waiting for @Vollstrecker to give me the green light and totally forgot about it.

**Comment by Vollstrecker** [comment]
Did I forget something? My list only contains reworking the actions.

**Comment by mrjimenez** [comment]
You and I:

https://github.com/pupnp/pupnp/pull/448#issuecomment-2222321087

**Comment by Vollstrecker** [comment]
k, I didn't understand that one completely but I'm pretty sure I've broke something on their side. While investigating I've found a little problem here which I don't understand why noone complained about. So with #450 merged I guess we're fine here.

**Comment by KarlStraussberger** [comment]
@mrjimenez 

I thought about something like this
```
diff --git a/upnp/src/threadutil/ThreadPool.c b/upnp/src/threadutil/ThreadPool.c
index b66ee93e..8ad19dd6 100644
--- a/upnp/src/threadutil/ThreadPool.c
+++ b/upnp/src/threadutil/ThreadPool.c
@@ -1067,6 +1067,13 @@ int ThreadPoolShutdown(ThreadPool *tp)
        return 0;
 }

+static int maxJobsTotal = DEFAULT_MAX_JOBS_TOTAL;
+
+void TPSetMaxJobsTotal(int mjt)
+{
+       maxJobsTotal = mjt;
+}
+
 int TPAttrInit(ThreadPoolAttr *attr)
 {
        if (!attr)
@@ -1078,7 +1085,7 @@ int TPAttrInit(ThreadPoolAttr *attr)
        attr->stackSize = DEFAULT_STACK_SIZE;
        attr->schedPolicy = DEFAULT_POLICY;
        attr->starvationTime = DEFAULT_STARVATION_TIME;
-       attr->maxJobsTotal = DEFAULT_MAX_JOBS_TOTAL;
+       attr->maxJobsTotal = maxJobsTotal;

        return 0;
 }
```
No public API, just the option to declare the function when you found it.

**Comment by KarlStraussberger** [comment]
I am still trying whether it works at all and will create a PR afterwards
